### ISSUE TITLE
Code for downloading pdf from OpenScience 

### ISSUE THREAD

**Issue by lizhenzhupearl** [mmore500/curaitor#12]

**Comment by mmore500** [comment]
I added a skeleton for the validation workflow that you can incorporate your code into!

- The GitHub actions page with "run workflow" button: <https://github.com/mmore500/curaitor/actions/workflows/validate.yaml>
- The source for the validation workflow content (we'll put the actual workflow here):  <https://github.com/mmore500/curaitor/blob/master/validate.py>
- The GitHub actions source file that runs the workflow: <https://github.com/mmore500/curaitor/blob/master/.github/workflows/validate.yaml>
