### ISSUE TITLE
Test if the number of output file is correct

### ISSUE THREAD

**Issue by Nanta-Sp** [mmore500/curaitor#15]
- check if the number of processed files equal to number of input files
OR
- check the number of output pdf file in the output folder equal to the number of input file

This will be used multiple time including
1. the crop page function (check for pdf files)
2. text mining (check for text files)

**Comment by Nanta-Sp** [comment]
Do we really need to do this?
If there is some unreadable file, then the number of output files will not be the same as the number of input files.
(isn't that the unreadable file will be skipped?)

**Comment by stkhuu** [comment]
> Do we really need to do this?
> If there is some unreadable file, then the number of output files will not be the same as the number of input files.
> (isn't that the unreadable file will be skipped?)


Testing file validity is sufficient and has been implemented. There will be error thrown if any of them can't be read. I will close this issue.
